[package]
name = "embedded_linux_eink_example"
version = "0.1.0"
authors = ["Christoph Groß <christoph-gross@mailbox.org>"]
edition = "2018"

[dependencies]

epd-waveshare = { path = "../../", default-features = false, features = ["epd1in54"]}

#epd-waveshare = { path = "../../"}
# 687496 -> 16868

embedded-hal = { version = "0.2.2", features = ["unproven"] }

stm32f1xx-hal = { version = "0.2", features = ["rt", "stm32f103" ] }
cortex-m = "0.5.0"
cortex-m-rt = { version = "0.6.6", features = ["device"] }
panic-semihosting = "0.5"
